### ISSUE TITLE
[feature request] Unnecessary parentheses in raise exception

### ISSUE THREAD

**Issue by Mogost** [jdufresne/flake8-raise#1]
@jdufresne Thanks for your plugin, I would like to offer one more check about exceptions

R102 Unnecessary parentheses in raise exception
```
if something:
    raise PermissionDenied()
```
Will result in the error:
R102 Unnecessary parentheses in raise exception

To fix, change to:

```
if something:
    raise PermissionDenied
```

If there is no difference then why write more?
However, there may be people who prefer the opposite so that the brackets are always there and you can do the reverse optional check.

**Comment by kingbuzzman** [comment]
While i agree with you, and i personally do not put `()` on exceptions that i dont care for it to have a message -- there are a lot of companies out there that use the [google style docs](http://google.github.io/styleguide/pyguide.html#244-decision) and they advocate for it. A blanket _must not have parentheses_ will not work, a possible flag may get you there however.

**Comment by jdufresne** [comment]
Good idea.

> A blanket must not have parentheses will not work, a possible flag may get you there however.

flake8 allows all rules to be turned on or off. For those that want the plugin but without some rules, they can use flake8's ignore feature: http://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html

**Comment by jdufresne** [comment]
I've implemented your suggestion. Let me know if you have a chance to test it with your use case. Thanks!

**Comment by Mogost** [comment]
> I've implemented your suggestion. Let me know if you have a chance to test it with your use case. Thanks!

I will test in a few days.

**Comment by Mogost** [comment]
False positive on case:
```python
def get_exception_cls():
    return ZeroDivisionError

def test():
    raise get_exception_cls()
```
and something like [that](https://github.com/pydota2/pydota2_archive/blob/f33233ee5393a248e9845bb25ff234bf7ac9ff82/pydota2/lib/run_parallel.py#L68)

**Comment by kingbuzzman** [comment]
@Mogost  this is why `# noqa: R102`  was created 😜

**Comment by Mogost** [comment]
@kingbuzzman Sure but https://www.python.org/dev/peps/pep-0008/#exception-names exceptions use formating rules as classes.
If your exception classes are similar to `get_exception_cls`, you have a bit more problems than having extra parentheses.

**Comment by kingbuzzman** [comment]
I'm not sure if i'm understanding you fully, you're saying that if someone does the code above they have to go through the trouble of adding the `# noqa: R102` ? As apposed to what?

PS. I asked to add it into the tests: https://github.com/jdufresne/flake8-raise/pull/2#issuecomment-577658195

**Comment by jdufresne** [comment]
@Mogost Are you suggesting to only warn when the exception uses `UpperCamelCase` formatting to cut down on the false positives?

**Comment by kingbuzzman** [comment]
I disagree with this, when trying to avoid false positives, you’ll only introduce more false positives. Python is a grownup language, let people decide what to exclude with a proven solution ie `noqa`

**Comment by jdufresne** [comment]
Okay, I've gone ahead and merged the feature. If there prove to be a large number of false positives, we can reevaluate if it needs to be tuned or is useful. Thanks everyone!

**Comment by jdufresne** [comment]
Version 0.0.5 was released today with this feature.

**Comment by Mogost** [comment]
> @Mogost Are you suggesting to only warn when the exception uses `UpperCamelCase` formatting to cut down on the false positives?

Yes, this is really what I had in mind.
But if you look at the problem as a whole, there is a way to avoid false positives completely.
For example [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) uses ast.NodeVisitor to operate with Type. 
It would probably be possible to check `issubclass` of `BaseException`.
But this is probably a rather complicated approach.
